# Generated by Django 5.1.3 on 2024-11-27 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('idioma', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('lido', 'Lido'), ('lendo', 'Lendo'), ('wishlist', 'Wishlist')], default='wishlist', max_length=10)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
